### ISSUE TITLE
Received messages count metric missing in Prometheus server

### ISSUE THREAD

**Issue by nedimdjulic** [eclipse-hono/hono#3468] opened 2023-02-28 14:48 UTC
We are using Eclipse Hono and the CoAP adapter (other adapters are disabled). Prometheus server is used as a scraper. 
What is needed is to see how many messages are being received at a given time. Reading older issues here, I found the metric `hono_messages_received_seconds_count` being mentioned and used. I believe this is what is needed. But after listing all of the available metrics in Prometheus server, that one is not present.
Is some additional configuration needed here or there is some other reason why this metric is not scraped?

Thanks in advance!

**Comment by xeniape** [comment] 2023-03-01 13:40
I can confirm the same situation with the MQTT Adapter. The provided grafana dashboards also reference this metric, while the metric itself seems to be missing.

**Comment by sophokles73** [comment] 2023-03-01 15:19
Please refer to the [Hono Metrics API documentation](https://www.eclipse.org/hono/docs/api/metrics/) for a description of the metrics collected by Hono.
In your particular case you will probably be interested in the *hono.telemetry.payload*.
Note that the *hono.telemetry.payload* DistributionSummary will result in the following two timeseries in Prometheus:
1. *hono_telemetry_payload_count* and
2. *hono_telemetry_payload_sum*

as described in [section 3.3 of the Micrometer docs](https://micrometer.io/docs/registry/prometheus)

The dashboard definitions that are part of the Hono chart seem to be referring to outdated meter names. Since these dashboards are not maintained in the Hono project, would you mind opening a corresponding issue in the [Eclipse Packages](https://github.com/eclipse/packages) project, where all of the Helm charts are being maintained?

**Comment by nihadtz** [comment] 2023-03-02 09:16
Thank you [sophokles73](https://github.com/sophokles73) i have added issue to the Eclipse packages repo.

Because we need this now i can make PR to that repo with changed Grafana dashboards. It will not be same anymore because messages are not same structure anymore and some filters will not work.

**Comment by sophokles73** [comment] 2023-03-02 09:24
sure, a PR will be most welcome :+1:

**Comment by xeniape** [comment] 2023-03-02 13:59
> Please refer to the [Hono Metrics API documentation](https://www.eclipse.org/hono/docs/api/metrics/) for a description of the metrics collected by Hono.
In your particular case you will probably be interested in the hono.telemetry.payload.

First of all thanks for your quick answer! I'm not sure if there is still something wrong with our configuration, we just deployed Hono with the provided Helm Chart on https://github.com/eclipse/packages only disabling adapters/components we don't need. One of this components is Prometheus since we already have a running instance of that. So I assume the refence in your link to "[Configuring Metrics](https://www.eclipse.org/hono/docs/admin-guide/monitoring-tracing-config/#enabling-collection-of-metrics)" does not apply here to enable Prometheus? This wouldn't in some way enable additional metrics, would it? Or did I understand something wrong?
Because at the moment the only metrics being returned from your referenced list are hono_tenants_total and hono_connections_unauthenticated

![image](https://user-images.githubusercontent.com/22775981/222448681-2739a8a0-d3d9-492d-9b17-ef9e1cadcdf0.png)

**Comment by sophokles73** [comment] 2023-03-02 14:44
The *metrics-prometheus* profile is being used by the release build that creates the Hono container images, so you do not need to do anything else in order to activate the metrics endpoint.
Do you already have devices connecting to the CoAP adapter and sending telemetry messages?

**Comment by xeniape** [comment] 2023-03-03 08:20
> Indeed, the meter is created as soon as the first value is to be reported. That happens when the first device connects to the adapter and sends some data ...

Then thank you very much for your clarification :)

**Comment by sophokles73** [comment] 2023-03-03 08:23
Let us know if it works so we can close this issue ...

**Comment by nihadMaestral** [comment] 2023-03-24 12:04
Yes you can close it, PR has been merged on packages repo

**Closed** 2023-03-24 15:19 UTC
Labels: question, Metrics
